apiVersion: v1
kind: Service
metadata:
  name: petclinic-service
  namespace: petclinic-dev
  labels:
    app: petclinic
    environment: dev
spec:
  type: NodePort
  ports:
  - port: 8085          #servizio esposto all'interno del cluster
    targetPort: 8080    #porta in ascolto all'interno del pod
    nodePort: 30082     #raggiungibile dall'esterno del cluster aka online
    name: http
  selector:
    app: petclinic   
