apiVersion: v1
kind: Service
metadata:
  name: petclinic-service
  namespace: petclinic-dev
  labels:
    app: petclinic
    environment: dev
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 8081
    nodePort: 30081
    name: http
  selector:
    app: petclinic 