apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: petclinic-staging

resources:
  - ../../base 
  - namespace.yaml

images:
  - name: ghcr.io/enea-dervishi/petclinic
    newName: ghcr.io/enea-dervishi/petclinic
    newTag: staging-5 